# pygame related
import pygame

WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 695
EVENTS_REFRESH_TIME = 0.1
GAME_NAME = 'game'
BACKGROUND = 'stick_AME\\Background.jpg'
COLOR_KEY_BACKGROUND = (255, 255, 255)

END_GAME_SCREEN_TIME = 5
# game related:
HORIZONTAL_WALKING_SPEED = 12.5
HORIZONTAL_AIR_SPEED = HORIZONTAL_WALKING_SPEED / 1.5

PLAYER_X_DIFF_LEGS_BODY = 10
PLAYER_Y_DIFF_LEGS_BODY = -pygame.image.load('stick_AME\\bow and arrow ani00.png').get_rect().height + 20
PLAYER_X_DIFF_LEGS_HEAD = 5
PLAYER_Y_DIFF_LEGS_HEAD = PLAYER_Y_DIFF_LEGS_BODY + pygame.image.load('stick_AME\\HEAD0.png').get_rect().height - 40

RELOAD_TIME = 0.8  # (sec)
G = 2
JUMP_VY = -34

# player one
_PLAYER_ONE_STARTING_POS_LEGS = (0, 400)
PLAYER_ONE_STARTING_X_LEGS, PLAYER_ONE_STARTING_Y_LEGS = _PLAYER_ONE_STARTING_POS_LEGS
PLAYER_ONE_STARTING_X_BODY, PLAYER_ONE_STARTING_Y_BODY = PLAYER_ONE_STARTING_X_LEGS + PLAYER_X_DIFF_LEGS_BODY, PLAYER_ONE_STARTING_Y_LEGS + PLAYER_Y_DIFF_LEGS_BODY
PLAYER_ONE_STARTING_X_HEAD, PLAYER_ONE_STARTING_Y_HEAD = PLAYER_ONE_STARTING_X_LEGS + PLAYER_X_DIFF_LEGS_HEAD, PLAYER_ONE_STARTING_Y_LEGS + PLAYER_Y_DIFF_LEGS_HEAD

# player two:
_PLAYER_TWO_STARTING_POS_LEGS = (500, 400)
PLAYER_TWO_STARTING_X_LEGS, PLAYER_TWO_STARTING_Y_LEGS = _PLAYER_TWO_STARTING_POS_LEGS
PLAYER_TWO_STARTING_X_BODY, PLAYER_TWO_STARTING_Y_BODY = PLAYER_TWO_STARTING_X_LEGS + PLAYER_X_DIFF_LEGS_BODY, PLAYER_TWO_STARTING_Y_LEGS + PLAYER_Y_DIFF_LEGS_BODY
PLAYER_TWO_STARTING_X_HEAD, PLAYER_TWO_STARTING_Y_HEAD = PLAYER_TWO_STARTING_X_LEGS + PLAYER_X_DIFF_LEGS_HEAD, PLAYER_TWO_STARTING_Y_LEGS + PLAYER_Y_DIFF_LEGS_HEAD

# conection related:
SERVER_IP = '127.0.0.1'
SERVER_PORT = 8000
